### ISSUE TITLE
težava pri uvozu tabele iz spletne strani

### ISSUE THREAD

**Issue by ztrojer** [ztrojer/APPR-2017-18#1]
Imam težavo pri uvozu prve tabele iz strani "http://www.eafo.eu/vehicle-statistics/m1".

**Comment by jaanos** [comment]
Stran pridobi podatke v tabelah z naslovov http://www.eafo.eu/charts/6689/vehicles_bev_table_graph in http://www.eafo.eu/charts/6689/vehicles_phev_table_graph, kjer so podatki predstavljeni v obliki JSON. Za uvoz prve tabele lahko narediš nekaj takega:
```R
library(httr)

link <- "http://www.eafo.eu/charts/6689/vehicles_bev_table_graph"
json <- GET(link) %>% content()
data <- json$data$rows %>% sapply(. %>% sapply(. %>% .$value)) %>% t() %>% data.frame()
colnames(data) <- json$data$cols %>% sapply(. %>% .$name)
```
Tukaj se torej uporabi funkcija `GET` iz knjižnice `httr`, ki zna podatke v obliki JSON že uvoziti v ustrezno obliko. Podatki so v polju `data`, ki vsebuje stolpce (`cols`, z imenom v polju `name`) in vrstice (`rows`, s podatkom v polju `value` vsake celice). Podobno bo deloval tudi uvoz za drugo tabelo.

Dobljeno razpredelnico bo seveda treba še urediti - številske podatke (vključno z deleži) bo treba pretvoriti v številke (`parse_number` iz knjižnice `readr`) ter pretvoriti v obliko *tidy data* (`melt` iz knjižnice `reshape2`).
