### ISSUE TITLE
Problem pri grafu 8

### ISSUE THREAD

**Issue by ztrojer** [ztrojer/APPR-2017-18#3]
Pozdravljeni, 

pri grafu 8 imam sledeče težave: (datoteka grafi.r)
1) imena držav niso poravnane z stolpci
2) v legendi bi rad imel samo leto 2016 in leto 2004, vendar ko naredim: `aes(x = reorder(DRZAVA, -VREDNOST), y = VREDNOST, fill = factor(LETO, labels = c("2004", "2016")))`, se mi na grafu obrneta deleža. 

Lep pozdrav

**Comment by jaanos** [comment]
Najprej, programa v mapi `vizualizacija` imata končnico `.R` (velika črka), tako da tako napiši tudi v poročilu, saj so nekateri sistemi občutljivi na velikost črk.

Pri parametru `fill` podaj samo `factor(LETO)`, brez parametra `labels`. Pri meni sicer oboje deluje enako - očitno je že v podatkih tako, da so nekatere države imele veliko večji delež leta 2004.

Sicer pa svetujem, da za vsako državo prikažeš dva stolpca, saj ni smiselno prikazovati vsote deležev po letih. Tako se bo tudi dalo za vsako državo bolj direktno primerjati deleža v obeh letih. Potem bo treba poskrbeti tudi za ustrezno ureditev, npr. po vrednosti za leto 2004 (trenutno namreč urejaš po vsoti). Ker so podatki ustrezno urejeni (najprej imaš podatke za 2004, nato pa v istem vrstnem redu še za 2016), lahko podatke za `reorder` dobiš tako, da dvakrat ponoviš podatke za leto 2004, npr.
```R
graf8 <- ggplot(tabela0416, aes(x = reorder(DRZAVA, rep(-VREDNOST[LETO == 2004], 2)),
                                y = VREDNOST, fill = factor(LETO))) +
  geom_col(position = "dodge") +
  labs(title ="Delež energije iz obnovljivih virov", x = "država",
       y = "delež energije iz obnovljivih virov", fill = "Leto") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 
```

**Comment by jaanos** [comment]
Še to sem pozabil omeniti - imena držav lahko poravnaš s parametrom `vjust` pri `axis.text.x` (sem dodal v zgornji primer). Načeloma `vjust = 0.5` pomeni sredinsko poravnavo vrstice, a se mi zdi, da vrednost `0.4` nekoliko boljše izgleda.

**Comment by ztrojer** [comment]
Imam problem pri aplikaciji shiny - Proizvedena električna energija po proizvodnih delih. Nameraval sem narediti tako, da bi obkljukal, katere tipe elektrarne želim prikazati na grafu, vendar mi to nikakor ni uspelo.

Zanima me tudi, kako prevesti poročilo, da deluje tako shiny kot vizualizacija.

Lep pozdrav

**Comment by jaanos** [comment]
V razpredelnici `tabela1` imaš v stolpcu `TIP` na začetku presledke. Najbolje bo, če se jih znebiš že pri uvozu:
```R
tabela1$TIP <- trimws(tabela1$TIP)
```
Potem lahko izbrane podatke prikažeš tako, da filtriraš po vrednostih iz `input$tip`. Da se ti na osi y ne pojavljajo številke v eksponentni notaciji, predlagam, da števila deliš s 1000 in poskrbiš za ustrezno oznako osi y, npr.
```R
  g2 <- ggplot(data = data %>% filter(TIP %in% input$tip),
               aes(x = LETO, y = VREDNOST/1000, color = TIP)) + geom_line(stat = "identity") +
    ylab("Proizvidnja (PJ)")
```

Ko boš prevajal poročilo, te bo vprašalo, ali ga želiš pognati kot Shiny - tedaj odgovoriš *Yes, Always*. V glavo poročila se bo dodala vrstica `runtime: shiny` (lahko je tudi sam dodaš), namesto gumba *Knit* pa se bo pojavil gumb *Run Document*, s katerim poženeš poročilo s Shinyjem.

Opažam še, da v podatkih nadomeščaš ime za Makedonijo s `Former Yugoslav`, potem pa v zemljevidu uporabiš to ime za države bivše Jugoslavije in Albanijo. Glede na to, da tvoji podatki vsebujejo podatke za vse države bivše Jugoslavije, to ni potrebno - za Makedonijo uporabi ime `Macedonia` (kakor je tudi v zemljevidu), za druge države pa se imena že ujemajo (oz. za BiH že poskrbiš).
