### ISSUE TITLE
Zaključek projekta

### ISSUE THREAD

**Issue by ztrojer** [ztrojer/APPR-2017-18#4]
Pozdravljeni, 

projekt sem dokončal, pošiljam v pregled.

**Comment by jaanos** [comment]
V redu, bom dodal povezavo na repozitorij za zagovore, tako da se lahko z @alenFMF domeniš za termin zagovora. Če boš še kaj spreminjal, mi prosim javi, da posodobim povezavo.

Svetoval bi še sledeče:
* Pri napovedi prodaje avtomobilov poskrbi, da se trendni črti prikažeta čez celoten obseg grafa (`fullrange = TRUE`) ter morda tudi odstrani območje napake (`se = FALSE`). Prav tako lahko poskrbiš za oznake osi x (da nimaš decimalk v letnicah) ter obsega osi y (glede na to, da gre za število, ni smiselno, da prikazuješ negativne vrednosti), npr.
```R
model4 <- graf3 + geom_smooth(method = "lm", fullrange = TRUE, se = FALSE) +
  ylim(0, 200000) + scale_x_continuous(breaks = seq(2010, 2020, 2))
```
* Pri napovedi porabe električne energije prikazuješ en model, napoveduješ pa z drugim. Svetujem, da tudi za prikaz na grafu uporabiš `gam`:
```R
  model1 <- ggplot(transport, aes(x = LETO, y = VREDNOST)) + geom_point() +
    geom_smooth(method = "gam", formula = y ~ s(x), fullrange = TRUE)
```
* V Shiny aplikaciji na zemljevidu deleža iz obnovljivih virov poskrbi za ustrezno oznako legende.
* V zavihku *Proizvedena električna energija po proizvodnih delih* poskrbi, da bo vsaj kak tip že privzeto izbran, tako da se bo takoj izrisal kak graf. To narediš tako, da funkciji `checkboxGroupInput` podaš parameter `selected` s seznamom izbranih vrednosti iz `choiceValues` (torej angleških imen).
* V glavi poročila kar pusti vrstico `runtime: shiny`, da te ne bo vsakič spraševalo, ali želiš pognati poročilo kot Shiny.

**Comment by ztrojer** [comment]
Projekt sem dopolnil, zato vas prosim če posodobite povezavo.

**Comment by jaanos** [comment]
V redu, sem posodobil.
